### ISSUE TITLE
Delete non records ???

### ISSUE THREAD

**Issue by BobBorges** [swerik-project/riksdagen-records#1]
I want to delete these files from the corpus. Please @MansMeg , @ninpnin @fredrik1984 have a look and give me the thumbs up or down.

- [ ] 1909/prot-1909----reg-01.xml
- [ ] 1909/prot-1909----reg-02.xml    
- [ ] 197677/prot-197677--.xml"
- [ ] 197778/prot-197778--.xml

**Comment by MansMeg** [comment]
Can you explain a little more? Are they empty?

**Comment by BobBorges** [comment]
The two in 1909 are not protocols. The other two look like this:
![image](https://github.com/swerik-project/riksdagen-records/assets/8887511/65e99e49-476a-410b-9c8c-91a735f088bd)

**Comment by MansMeg** [comment]
If they are not records, they should be removed. 

The thing from the 70s look like a record? What is the problem?

**Comment by BobBorges** [comment]
>The thing from the 70s look like a record? What is the problem?

They're like cover sheets, not actual records.
![image](https://github.com/swerik-project/riksdagen-records/assets/8887511/3d1272d2-3eab-4e11-9dfd-64e343a9f2e5)

Also the file names with a different pattern mess with other things.

**Comment by BobBorges** [comment]
Ah, and I would like this one to go as well: prot-200708--678.xml

![image](https://github.com/swerik-project/riksdagen-records/assets/8887511/09a6b85e-2e11-431b-94af-8d27197e119d)

**Comment by ninpnin** [comment]
I think these should be removed.

**Comment by MansMeg** [comment]
I agree with @ninpnin . These are not records. I would remove those as well.

**Comment by MansMeg** [comment]
Also the felaktigt protokoll should be removed.

**Comment by BobBorges** [comment]
Done https://github.com/swerik-project/riksdagen-records/commit/c5cdcec2a2731adf67ef5467c08e8246d935299c
