### ISSUE TITLE
Gold standard for dates

### ISSUE THREAD

**Issue by ninpnin** [swerik-project/riksdagen-records#16]
Due to unknown quality at the moment, we want a gold standard for dates. I have generated a CSV file with 1 random protocol per year and chamber:

[date-sample.csv](https://github.com/swerik-project/riksdagen-records/files/15130662/date-sample.csv)

In the true-dates column, fill in all the dates of the protocol. Use the YYYY-MM-DD format. This should be relatively straightforward: the date(s) are usually either on the front page, or in the margin notes. However you might need to go through most pages in some records to find them all.

**Comment by todomoldovan** [comment]
I can take this

**Comment by todomoldovan** [comment]
[date-sample.csv](https://github.com/swerik-project/riksdagen-records/files/15147011/date-sample.csv)

Some notes: many protocols circa 1950-1990 span a few days so I included the interval of dates and made a note in the comments column. Could not find 4 protocols from the 1990s via the link in the spreadsheet or manually. Left blank and included a comment.

**Comment by ninpnin** [comment]
Thanks @todomoldovan !

I think protocols spanning multiple days is more common. For instance, prot_1926__fk__28 has both 1926-04-23 and 1926-04-24.

Could you double check the ones where you have only one date? Open the last page of the protocol, and see if it is labeled with another date than in the CSV, and if yes, fix it in the CSV.

The 90s issue is not a problem–we don't have access to any printed protocols then anyway.

**Comment by todomoldovan** [comment]
Will have it done by the end of the day tomorrow.

**Comment by MansMeg** [comment]
- [ ] Calculate the quality based on the data
- [ ] Add the gold standard to the quality folder of the repo

**Comment by MansMeg** [comment]
We hade a short discussion on how to measure the quality. I suggest we use the intersection of unions metric. It is used in computer vision to assess performance of object detection boxes:
https://pyimagesearch.com/2016/11/07/intersection-over-union-iou-for-object-detection/

Also called Jaccard index:
https://en.wikipedia.org/wiki/Jaccard_index

But we can use it in a one-dimensional sense based on individual dates.

**Example:**
Gold standard: 2012-04-13--2012-04-15, 2012-04-17 
Prediction: 2012-04-14--2012-04-15, 2012-14-18

Union:  2012-04-13--2012-04-15, 2012-04-17--2012-14-18
Intersection: 2012-04-14--2012-04-15

Jaccard: 2/5 = 0.4

**Comment by ninpnin** [comment]
Fair enough! I think I'll estimate 

$$
\begin{aligned}
&\mathbb E[J(Y, \hat Y)] \\
&\mathbb P( J(Y, \hat Y) = 1) \\
&\mathbb P( J(Y, \hat Y) > 0) \\
\end{aligned}
$$

then, i.e. the expectation, proportion of perfect matches and proportion of any overlap.

**Comment by MansMeg** [comment]
Sounds like good idea!

**Comment by ninpnin** [comment]
E[J] 0.8149223606216616
P(J == 1) 0.7265625
P(J > 0) 0.93359375

**Comment by ninpnin** [comment]
I found some errors in the gold standard. I fixed them, and now the results are:

E[J] 0.8782036082103943
P(J == 1) 0.7890625
P(J > 0) 1.0

i.e. 79% of dates are fully correct, average Jaccard coefficient 0.88, and there is some overlap of the true and scraped  dates in 100% of the sample. Pretty good I think.

**Comment by ninpnin** [comment]
Here's the corrected gold standard: [date-sample-corrected.csv](https://github.com/user-attachments/files/16798628/date-sample-corrected.csv)

**Comment by ninpnin** [comment]
Additionally, the scraped date range contains the true date range in 99.2% of the sample.

**Comment by ninpnin** [comment]
The gold standard is done, let's continue discussion in #25 and https://github.com/swerik-project/scripts/pull/8
