### ISSUE TITLE
Add dates quality to the records repo as quality dimension

### ISSUE THREAD

**Issue by MansMeg** [swerik-project/riksdagen-records#25]
Students has manually coded this so we should use it for dynamic estimation of dates quality

**Comment by BobBorges** [comment]
Which dates are you referring to?

**Comment by BobBorges** [comment]
Add script functions to the dynamic readme, not as a unit test.

**Comment by MansMeg** [comment]
This has expanded now to include titles. See https://github.com/swerik-project/the-swedish-parliament-corpus/issues/44
