### ISSUE TITLE
Pre-train a transformer model on the parliamentary corpus

### ISSUE THREAD

**Issue by MansMeg** [swerik-project/riksdagen-records#27]

**Comment by ninpnin** [comment]
Why is this here?

**Comment by ninpnin** [comment]
Followed here https://github.com/swerik-project/pretraining_plm/issues

**Comment by MansMeg** [comment]
Oh. I wrote down that we should have an issue on the canban board on this.

**Comment by ninpnin** [comment]
Fair enough. I just get existential dread when it feels like the issues are getting out of hand .. 😅
