### ISSUE TITLE
Move the quality dimension data to the right spot

### ISSUE THREAD

**Issue by MansMeg** [swerik-project/riksdagen-records#29]
Look in our paper where to put it and put it in the right repository.

See:
https://docs.google.com/document/d/1GauUJAx__rGkdMe5N54FxTT3jdcCvVnvHi_1-Q6AipA/edit#heading=h.bszvee3gqdk7

## to do

- [x] proposals
- [x] decision
- [x] implement

### Records corpus
- [x] OCR
- [x] segmentation
- [x] speaker mapping

### Persons corpus

- [x] MP coverage

**Comment by BobBorges** [comment]
This is relevant for the whole project, not only the records-corpus.

**Comment by MansMeg** [comment]
Thats true. I guess we should propose a decision on this. i can try to do this.
