### ISSUE TITLE
Ambiguous note-seg segments

### ISSUE THREAD

**Issue by vgkz** [swerik-project/riksdagen-records#38]
Some text sequences cannot be clearly labeled as a note or a speech segment due to the segment containing parts of a speech and a note simultaneously. To improve the note seg labeling, ambiguous segments would need to be identified and then split into a note segment and seg segment. 

Examples from records prot-1912--fk--003.xml, prot-1912--fk--011.xml, prot-1923--ak--018.xml, prot-1933--fk--019.xml can be seen in #37.

**Comment by ninpnin** [comment]
Seems to be a duplicate of #11 , @vgkz please confirm. I checked the first three, they were all margin notes merged into the bodytext, which is a known issue.

**Comment by vgkz** [comment]
Good point, its a duplicate.
