### ISSUE TITLE
Revert introductions being overriden by title detection

### ISSUE THREAD

**Issue by ninpnin** [swerik-project/riksdagen-records#43]
While the title detection generally performed well, there were some introductions that were labeled as titles. 

<img width="1062" alt="Screenshot 2024-09-13 at 09 34 51" src="https://github.com/user-attachments/assets/84545562-519a-4886-a35b-257c03ed0ac4">

We probably want to revert this. So let's run the intro detection on ```<note type="title">``` elements.

In addition to this, we need to rerun the mapping algorithm, as the new ```<u>``` elements are labeled ```unknown``` right now.

**Comment by fredrik1984** [comment]
Ok, good that you noted this!
