### ISSUE TITLE
Create a public discussion forum for users to report errors in the speech data

### ISSUE THREAD

**Issue by fredrik1984** [swerik-project/riksdagen-records#45]
Users of the Swerik data, for example through the SweDeb interface (https://swedeb.se/public/index.html#/about), are likely to find errors about the data (OCR, segmentation, wrong metadata, etc) that they want to report.

We should create a public discussion forum on GitHub where users can write about these errors (specific and general) and also read what others have written. SweDeb will link to this forum. 

We could pre-create a couple of discussion streams like OCR errors, segmentation errors, and wrong/missing MP/speech metadata. 

Exactly how much such a forum will be used, and how we will administrate it, need to be an open question. 

At first, we create a discussion forum for the speech records but this could of course also expand to the other parliamentary data types.

**Comment by BobBorges** [comment]
Don't we already have this? GitHub discussions.

**Comment by fredrik1984** [comment]
I mean we should use the GitHub discussions and not create a new forum for this. But I guess we need to organize the discussion forum in the way we want it, no?

**Comment by BobBorges** [comment]
Are you happy if we add something like "Error Reporting" as a category on the left here?
![image](https://github.com/user-attachments/assets/fc3a18a9-6bd6-4c8c-bf2f-5713b229d3f1)

**Comment by fredrik1984** [comment]
Yes, that would work fine. We should start simple since we don't know how busy such an error forum will be.

**Comment by BobBorges** [comment]
Here's a link SWEDEB can use: https://github.com/orgs/swerik-project/discussions/categories/report-errors

![image](https://github.com/user-attachments/assets/453e877d-deb6-4205-9a32-2df0866e28e5)
